movieShow:
  method: 'get'
  path: movies/{id:[0-9]+}
  controller: App\Controller\HomeController
  action: show

movieIndex:
  method: 'get'
  path: movies
  controller: App\Controller\HomeController
  action: index